[[headers]]
  for = "/static/games/html/isaacrebirth"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
  
[[headers]]
  for = "/static/vciframe.html"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"